### PR TITLE
List the dimensions of datasets

### PR DESCRIPTION
**Pull request by bbucior**
Added columns to the datasets html and csv lists with a summary of the dataset size (rows by columns). In cases where the dataset is a numeric vector, list its size as length by one. Also updated the README based on the number of entries in the updated datasets.csv.

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Looks good and useful. Why do some files have a bunch of extraneous `^M` characters?

**Comment by vincentarelbundock** [comment]
looks good, thanks!

**Comment by bbucior** [comment]
I couldn't figure out why my configuration wasn't exporting the line endings correctly, so I ran the Makefile within a Linux VM.  Do you want me to squash the commits?

**Comment by vincentarelbundock** [comment]
Looks good over here. I don't think there's need to do anything else.

**Comment by vincentarelbundock** [comment]
I think next time it might be best to just update the script, and not the data. Makes it easier to review, and I can run the update locally.

**Pull request merged**
